// Enterprise Micro-Skill Knowledge Graph DAG Definition (15-Module 12 LPA Analytics Track)
// Maps foundational to advanced skills with strict prerequisite edges.

export const CORE_SKILL_GRAPH = [
  // ── MODULE 0: EXCEL + BUSINESS PRODUCTIVITY ──
  {
    slug: "excel-lookups-formulas",
    name: "Modern Lookups & Logic (XLOOKUP, INDEX/MATCH, Dynamic Arrays)",
    category: "EXCEL",
    bloomLevel: 2,
    dayNumber: 1,
    prerequisites: [],
    description: "Two-way lookups, spill ranges (FILTER, UNIQUE, SORT), error handling, nested logical conditions.",
  },
  {
    slug: "excel-pivot-tables",
    name: "Multi-Dimensional Pivot Tables & Calculated Fields",
    category: "EXCEL",
    bloomLevel: 3,
    dayNumber: 2,
    prerequisites: ["excel-lookups-formulas"],
    description: "Dynamic table sources, tabular layout, calculated fields, timeline slicers, report connections.",
  },
  {
    slug: "excel-financial-modeling",
    name: "Financial Modeling (3-Statement Architecture, DCF, CAGR, LTV:CAC)",
    category: "EXCEL",
    bloomLevel: 4,
    dayNumber: 3,
    prerequisites: ["excel-pivot-tables"],
    description: "Compound growth rates, discounted cash flows, Net Present Value, IRR, and SaaS unit economics.",
  },
  {
    slug: "excel-sensitivity-analysis",
    name: "Scenario Planning & Sensitivity Analysis (What-If, Goal Seek)",
    category: "EXCEL",
    bloomLevel: 4,
    dayNumber: 4,
    prerequisites: ["excel-financial-modeling"],
    description: "Two-variable data tables, Scenario Manager, Goal Seek break-even solver, conditional heatmaps.",
  },
  {
    slug: "excel-power-query-etl",
    name: "Excel Power Query (Get & Transform M-Code Pipelines)",
    category: "EXCEL",
    bloomLevel: 3,
    dayNumber: 5,
    prerequisites: ["excel-lookups-formulas"],
    description: "Folder file combinations, unpivoting cross-tabs, type coercion, repeatable data cleaning DAGs.",
  },
  {
    slug: "excel-executive-dashboards",
    name: "C-Suite Executive Dashboards & Boardroom Visual Synthesis",
    category: "EXCEL",
    bloomLevel: 5,
    dayNumber: 6,
    prerequisites: ["excel-pivot-tables", "excel-sensitivity-analysis"],
    description: "3-sheet architecture, KPI cards with unicode deltas, sparklines, clean boardroom typography.",
  },

  // ── MODULE 1: PRODUCTION SQL & ANALYTICAL PROBLEM SOLVING ──
  {
    slug: "sql-select-filter",
    name: "Relational Filtering (WHERE, IN, BETWEEN)",
    category: "SQL",
    bloomLevel: 2,
    dayNumber: 7,
    prerequisites: [],
    description: "Predicate evaluation, index seek vs scan, Boolean logic on relational tuples.",
  },
  {
    slug: "sql-null-semantics",
    name: "Three-Valued Logic & NULL Handling (COALESCE, IS NULL)",
    category: "SQL",
    bloomLevel: 3,
    dayNumber: 7,
    prerequisites: ["sql-select-filter"],
    description: "Handling UNKNOWN truth states in SQL predicates and aggregations.",
  },
  {
    slug: "sql-joins-inner-left",
    name: "Relational Joins (INNER & LEFT)",
    category: "SQL",
    bloomLevel: 3,
    dayNumber: 7,
    prerequisites: ["sql-select-filter", "sql-null-semantics"],
    description: "Hash, Merge, and Nested Loop join mechanics on 1:N relations.",
  },
  {
    slug: "sql-fanout-mitigation",
    name: "Join Fan-Out & Multi-Table Aggregation Traps",
    category: "SQL",
    bloomLevel: 4,
    dayNumber: 7,
    prerequisites: ["sql-joins-inner-left"],
    description: "Preventing duplicate row multiplication when joining 1:N and M:N child tables.",
  },
  {
    slug: "sql-grouping-aggregations",
    name: "Grouping & Aggregate Computations (GROUP BY, HAVING)",
    category: "SQL",
    bloomLevel: 3,
    dayNumber: 8,
    prerequisites: ["sql-joins-inner-left"],
    description: "Pre-aggregations, cardinality reduction, and conditional HAVING filters.",
  },
  {
    slug: "sql-cte-subqueries",
    name: "Common Table Expressions (CTEs) & Modular SQL",
    category: "SQL",
    bloomLevel: 3,
    dayNumber: 8,
    prerequisites: ["sql-grouping-aggregations"],
    description: "Structuring readable, reproducible analytic pipelines using WITH clauses.",
  },
  {
    slug: "sql-window-partition-order",
    name: "Window Functions: PARTITION BY & ORDER BY",
    category: "SQL",
    bloomLevel: 4,
    dayNumber: 9,
    prerequisites: ["sql-cte-subqueries"],
    description: "Evaluating analytical computations over row partitions without collapsing rows.",
  },
  {
    slug: "sql-window-ranking",
    name: "Ranking Functions (ROW_NUMBER, RANK, DENSE_RANK, NTILE)",
    category: "SQL",
    bloomLevel: 4,
    dayNumber: 9,
    prerequisites: ["sql-window-partition-order"],
    description: "Resolving ties, leaderboards, top-N per category analytics.",
  },
  {
    slug: "sql-window-offset",
    name: "Offset Functions (LAG, LEAD) & Delta Tracking",
    category: "SQL",
    bloomLevel: 4,
    dayNumber: 10,
    prerequisites: ["sql-window-partition-order"],
    description: "Inter-row comparison, period-over-period growth, sessionization.",
  },
  {
    slug: "sql-window-framing",
    name: "Window Framing (ROWS vs RANGE vs GROUPS BETWEEN)",
    category: "SQL",
    bloomLevel: 5,
    dayNumber: 10,
    prerequisites: ["sql-window-ranking", "sql-window-offset"],
    description: "Sliding and cumulative frame specifications for rolling 7-day averages and moving metrics.",
  },
  {
    slug: "sql-cohort-retention",
    name: "Cohort Retention & Activity Matrix Modeling",
    category: "SQL",
    bloomLevel: 5,
    dayNumber: 11,
    prerequisites: ["sql-window-framing", "sql-window-offset"],
    description: "Month-0 to Month-12 retention matrices, churn attribution, active user modeling.",
  },
  {
    slug: "sql-query-optimization",
    name: "Query Execution Plans & B-Tree Index Optimization",
    category: "SQL",
    bloomLevel: 5,
    dayNumber: 12,
    prerequisites: ["sql-fanout-mitigation", "sql-cohort-retention"],
    description: "EXPLAIN QUERY PLAN, index selectivity, Sargable predicates, eliminating table scans.",
  },

  // ── MODULE 2: DATA MODELING & DATA WAREHOUSING ──
  {
    slug: "dw-star-snowflake-schema",
    name: "Kimball Dimensional Modeling (Star vs Snowflake)",
    category: "DATA_MODELING",
    bloomLevel: 4,
    dayNumber: 13,
    prerequisites: ["sql-joins-inner-left", "sql-grouping-aggregations"],
    description: "Fact vs Dimension tables, grain definition, surrogate keys, conformed dimensions.",
  },
  {
    slug: "dw-scd-slowly-changing-dimensions",
    name: "Slowly Changing Dimensions (SCD Type 1, 2, 3)",
    category: "DATA_MODELING",
    bloomLevel: 5,
    dayNumber: 35,
    prerequisites: ["dw-star-snowflake-schema"],
    description: "Tracking customer address & status history over time using start_date and end_date.",
  },

  // ── MODULE 3: ENTERPRISE POWER BI + ADVANCED DAX ──
  {
    slug: "bi-dax-evaluation-context",
    name: "DAX Context Transition (Row vs Filter Context & CALCULATE)",
    category: "POWER_BI",
    bloomLevel: 5,
    dayNumber: 14,
    prerequisites: ["dw-star-snowflake-schema"],
    description: "Mastering CALCULATE, context transition, filter expansion in Tabular semantic models.",
  },
  {
    slug: "bi-dax-time-intelligence",
    name: "DAX Time Intelligence (YTD, MTD, SAMEPERIODLASTYEAR)",
    category: "POWER_BI",
    bloomLevel: 4,
    dayNumber: 15,
    prerequisites: ["bi-dax-evaluation-context"],
    description: "Fiscal calendars, dynamic baseline comparisons, rolling period measures.",
  },
  {
    slug: "bi-security-rls",
    name: "Row-Level Security (RLS) & Performance Optimization",
    category: "POWER_BI",
    bloomLevel: 4,
    dayNumber: 16,
    prerequisites: ["bi-dax-evaluation-context"],
    description: "Static & dynamic RLS roles via USERPRINCIPALNAME, DAX Studio query plan tuning.",
  },

  // ── MODULE 4: PYTHON FOR ANALYTICS & AUTOMATION ──
  {
    slug: "python-pandas-vectorization",
    name: "Vectorized Pandas Transformations",
    category: "PYTHON",
    bloomLevel: 3,
    dayNumber: 25,
    prerequisites: ["sql-grouping-aggregations"],
    description: "Broadcasting, memory-efficient data transformations without slow Python for-loops.",
  },
  {
    slug: "python-cleaning-missing-data",
    name: "Data Imputation & Anomaly Cleansing",
    category: "PYTHON",
    bloomLevel: 3,
    dayNumber: 26,
    prerequisites: ["python-pandas-vectorization"],
    description: "Outlier detection (IQR, Z-Score), forward/backward fills, defensive type coercion.",
  },
  {
    slug: "python-rest-api-ingestion",
    name: "REST API Extraction & Rate-Limit Handling",
    category: "PYTHON",
    bloomLevel: 4,
    dayNumber: 29,
    prerequisites: ["python-cleaning-missing-data"],
    description: "Token auth, exponential backoff, pagination, idempotency in ingestion scripts.",
  },

  // ── MODULE 5: ETL/ELT & DATA PIPELINES ──
  {
    slug: "pipeline-incremental-loads",
    name: "Incremental Loads & Change Data Capture (CDC)",
    category: "DATA_ENGINEERING",
    bloomLevel: 4,
    dayNumber: 31,
    prerequisites: ["python-rest-api-ingestion", "dw-star-snowflake-schema"],
    description: "Watermarking, high-watermark delta queries, staging to production pipelines.",
  },
  {
    slug: "pipeline-data-quality-checks",
    name: "Automated Data Validation & Circuit Breakers",
    category: "DATA_ENGINEERING",
    bloomLevel: 4,
    dayNumber: 32,
    prerequisites: ["pipeline-incremental-loads"],
    description: "Row count anomaly detection, null threshold alarms, alerting before dashboard refresh.",
  },

  // ── MODULE 6: ANALYTICS ENGINEERING (dbt) ──
  {
    slug: "dbt-models-transformations",
    name: "dbt Core Models & Jinja Templating",
    category: "ANALYTICS_ENGINEERING",
    bloomLevel: 4,
    dayNumber: 40,
    prerequisites: ["sql-cte-subqueries", "dw-star-snowflake-schema"],
    description: "Ref macros, source fresh testing, modular SQL staging and marts architecture.",
  },
  {
    slug: "dbt-testing-ci-cd",
    name: "dbt Automated Testing, Lineage & CI/CD",
    category: "ANALYTICS_ENGINEERING",
    bloomLevel: 5,
    dayNumber: 42,
    prerequisites: ["dbt-models-transformations"],
    description: "Unique & not_null tests, accepted values, auto-generated docs, GitHub Actions PR checks.",
  },

  // ── MODULE 7: BUSINESS & PRODUCT ANALYTICS ──
  {
    slug: "product-funnel-conversion",
    name: "Conversion Funnels & Drop-Off Diagnostics (AARRR)",
    category: "PRODUCT_ANALYTICS",
    bloomLevel: 4,
    dayNumber: 19,
    prerequisites: ["sql-cohort-retention"],
    description: "Pirate metrics, multi-step funnel drop-off calculation, step-over-step velocity.",
  },
  {
    slug: "product-ltv-cac-economics",
    name: "Customer Unit Economics & LTV:CAC Payback",
    category: "PRODUCT_ANALYTICS",
    bloomLevel: 5,
    dayNumber: 20,
    prerequisites: ["product-funnel-conversion"],
    description: "Blended vs paid CAC, payback period in months, gross margin adjusted LTV.",
  },

  // ── MODULE 8: POWER PLATFORM & WORKFLOW AUTOMATION ──
  {
    slug: "power-platform-automations",
    name: "Enterprise Workflow Automation (Power Automate & n8n)",
    category: "AUTOMATION",
    bloomLevel: 4,
    dayNumber: 38,
    prerequisites: ["pipeline-data-quality-checks"],
    description: "Webhook triggers, automated incident escalation, executive Slack/Teams KPI alerts.",
  },

  // ── MODULE 9: AI FOR ANALYTICS ──
  {
    slug: "ai-text-to-sql-agents",
    name: "LLM Text-to-SQL & Analytical Autonomous Agents",
    category: "AI_ANALYTICS",
    bloomLevel: 5,
    dayNumber: 37,
    prerequisites: ["sql-cte-subqueries", "python-pandas-vectorization"],
    description: "Few-shot prompting, schema pruning, AST SQL validation, safe sandboxed execution.",
  },

  // ── MODULE 10: CLOUD & MODERN DATA PLATFORMS ──
  {
    slug: "cloud-snowflake-fabric-lakehouse",
    name: "Modern Cloud Lakehouse (Snowflake / Fabric)",
    category: "CLOUD_DATA",
    bloomLevel: 4,
    dayNumber: 61,
    prerequisites: ["dw-star-snowflake-schema", "dbt-models-transformations"],
    description: "Medallion architecture (Bronze/Silver/Gold), virtual warehouse sizing, cost governance.",
  },

  // ── MODULE 11: DATA GOVERNANCE, QUALITY & SECURITY ──
  {
    slug: "gov-dpdp-pii-masking",
    name: "Enterprise Data Governance & DPDP 2023 Compliance",
    category: "DATA_GOVERNANCE",
    bloomLevel: 5,
    dayNumber: 49,
    prerequisites: ["bi-security-rls"],
    description: "India DPDP Act 2023, PII hashing, dynamic column masking, audit logging lineage.",
  },

  // ── MODULE 12: BUSINESS ANALYSIS & STAKEHOLDER ENGINEERING ──
  {
    slug: "ba-brd-frd-user-stories",
    name: "BRD / FRD Authoring & Agile Scrum Requirements",
    category: "BUSINESS_ANALYSIS",
    bloomLevel: 4,
    dayNumber: 55,
    prerequisites: ["product-funnel-conversion"],
    description: "Gherkin BDD scenarios, stakeholder conflict resolution, Jira backlog grooming.",
  },

  // ── MODULE 13: STATISTICS, EXPERIMENTATION & COMMERCIAL ANALYTICS ──
  {
    slug: "stats-ab-testing-experimentation",
    name: "Statistical Hypothesis Testing & A/B Experimentation",
    category: "STATISTICS",
    bloomLevel: 5,
    dayNumber: 22,
    prerequisites: ["product-ltv-cac-economics"],
    description: "Power analysis, sample sizing, p-values, Sample Ratio Mismatch (SRM) diagnostics.",
  },

  // ── MODULE 14: BIG 4 INTERVIEW + CASE STUDY + JOB ENGINE ──
  {
    slug: "interview-minto-pyramid-defense",
    name: "McKinsey Minto Pyramid Boardroom Presentation",
    category: "EXECUTIVE_COMMUNICATION",
    bloomLevel: 6,
    dayNumber: 67,
    prerequisites: ["product-ltv-cac-economics", "gov-dpdp-pii-masking"],
    description: "Top-down executive communication, answer-first synthesis, defending architecture in live grilling.",
  }
];
